### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by askonomm** [dashyme/dashy-identity#1]
In formats such as:

- Vector (.ai)
- Vector (.svg)
- Vector (.pdf)
- Photoshop (.psd)
- Fireworks (.fw.png)
- Image (.png)
- Transparent image (.png)

**Comment by askonomm** [comment]
@GerttuB https://github.com/dashyme/dashy-identity/blob/master/dolphin.pdf

Dolphin as our mascot / Icon?

"Dashy Dolphin"

**Comment by GerttuB** [comment]
Esialgu ma ei olnud vaimustuses delfiini kasutamisest, kui ma tutvusin dedlfiini sümbolismiga ning see sobib. 
Mulle äkki meeldiks, kui meie nimes oleks "D" tehtud delfiinist, kuid ma mõtlen, et äkki seda on liiga raske presenteerida nii, et see oleks ka ilus.

**Comment by askonomm** [comment]
The dolphin looks like a lowercase "d", so why not, good idea! I'll see if I can make a sample of it.

**Comment by askonomm** [comment]
Updated version: https://github.com/dashyme/dashy-identity/blob/be21ea9ea34677832c8a3f7aa2879c6e760d4e73/dolphin.pdf @GerttuB

**Comment by GerttuB** [comment]
@askonomm It looks like "Cashy". https://www.pinterest.com/pin/46373071133540493/ -  Maybe this will give you some inspiration.

**Comment by GerttuB** [comment]
@askonomm 
https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSwCI46dyz9_ju5WYj05i25dzq6cJgnG4kGYpYagzDD1FV_XxUYlQ

**Comment by askonomm** [comment]
Take two: https://github.com/dashyme/dashy-identity/blob/371e167f3a905f092ac9dfb1191f684085f37e65/dolphin.pdf

I flipped the dolphin, made it a bit more awkward and unified the letters. There's some improvements to do still, like the "y" is a bit too skinny and the hands of the dolphin look a bit weird, but I kind of like it. Thoughts?

**Comment by GerttuB** [comment]
It's better but...I don't like that letters are that close to each other.
I have an idea to connect "y" and dolphin. Gonna explain that tomorrow.
@askonomm

**Comment by askonomm** [comment]
As per our discussion on Facebook, we've concluded that we're happy with the result we have now, and that if we were to do additional changes, it's when we have an actual illustrator at hand.
